[package]
name = "bitvm"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvm_types = { path = "../bitvm-types" }
pest = { version = "2" }
pest_derive = { version = "2" }
bitcoin = "0.30.1"
sha2 = "0.10.8"
rand = "0.8.4"
